/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Inferencia.Kohonen;
import Inferencia.ManejoArchivos;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author roberto
 */
public class Ventana extends javax.swing.JFrame {

    Kohonen k;
    /**
     * Creates new form Ventana
     */
    
    ManejoArchivos archivo;
    
    public Ventana() {
        initComponents();
        archivo = new ManejoArchivos();
        if(archivo.existeArchivo("reglas.dat"))
            k = new Kohonen();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnInsertaReglas = new javax.swing.JButton();
        btnUpdateRegla = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRecuperaReglas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEntrenamiento = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaEntrenamiento = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnInferencia = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areraInferencia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema experto neuronal");
        setBackground(java.awt.Color.white);

        jTabbedPane1.setBackground(java.awt.Color.white);
        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        btnInsertaReglas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnInsertaReglas.setText("Insertar reglas");
        btnInsertaReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertaReglasActionPerformed(evt);
            }
        });

        btnUpdateRegla.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdateRegla.setText("Modificar reglas");
        btnUpdateRegla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateReglaActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDelete.setText("Borrar reglas");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRecuperaReglas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnRecuperaReglas.setText("Mostrar Reglas");
        btnRecuperaReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperaReglasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Reglas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecuperaReglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInsertaReglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateRegla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(335, 335, 335))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInsertaReglas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateRegla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRecuperaReglas)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("CRUD", jPanel1);

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setText("Entrenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        areaEntrenamiento.setColumns(20);
        areaEntrenamiento.setRows(5);
        jScrollPane2.setViewportView(areaEntrenamiento);

        javax.swing.GroupLayout btnEntrenamientoLayout = new javax.swing.GroupLayout(btnEntrenamiento);
        btnEntrenamiento.setLayout(btnEntrenamientoLayout);
        btnEntrenamientoLayout.setHorizontalGroup(
            btnEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEntrenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrenamientoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(btnEntrenamientoLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        btnEntrenamientoLayout.setVerticalGroup(
            btnEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEntrenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Entrenamiento", btnEntrenamiento);

        btnInferencia.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnInferencia.setText("Iniciar");
        btnInferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInferenciaActionPerformed(evt);
            }
        });

        areraInferencia.setColumns(20);
        areraInferencia.setRows(5);
        jScrollPane3.setViewportView(areraInferencia);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInferencia)
                        .addContainerGap(741, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInferencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Inferencia", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertaReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertaReglasActionPerformed

        if(txtArea.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Text Area vacío");
        else
        {
            archivo.sobreescribir("reglas.dat", txtArea.getText().toString());
            JOptionPane.showMessageDialog(null, "Reglas guardadas en archivo");
        }
    }//GEN-LAST:event_btnInsertaReglasActionPerformed

    private void btnUpdateReglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateReglaActionPerformed
        
        archivo.elminarArchivoReglas("reglas.dat");
        archivo.sobreescribir("reglas.dat", txtArea.getText());
//        ArrayList <String> array;
//        array=archivo.recuperaSucesores("reglas.dat");
//        for (int i = 0; i < array.size(); i++) {
//            System.out.println(array.get(i));
//            
//        }  
    }//GEN-LAST:event_btnUpdateReglaActionPerformed

    private void btnRecuperaReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperaReglasActionPerformed
        ArrayList<String> array;
        array=archivo.recuperarReglas("reglas.dat");
        for (int i = 0; i < array.size(); i++) 
        {
            txtArea.append(array.get(i));
            txtArea.append("\n");
        }
    }//GEN-LAST:event_btnRecuperaReglasActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
     
        archivo.elminarArchivoReglas("reglas.dat");
        JOptionPane.showMessageDialog(null, "Archivo eliminado");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String pesos = "PESOS INICIALES\n";
       
        for (double [] peso : k.pesos){
            for (int j = 0; j < peso.length; j++) 
                pesos = pesos + String.format("%.2f",peso[j])+"\t";
            pesos = pesos+"\n";
            
        }
      
        k.Entrenamiento(); //Entrenar la red
        k.sincronizacion();
        
        pesos = pesos + "PESOS ENTRENADOS\n";
        for (double [] peso : k.pesos){
            for (int j = 0; j < peso.length; j++) 
                pesos = pesos + String.format("%.2f",peso[j])+"\t";
            pesos = pesos+"\n";
            
        }
        areaEntrenamiento.setText(pesos);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInferenciaActionPerformed
       String resultadoInferencia = "JUSTIFICACIÓN Y RESULTADO\n";
        double [] patron = new double[k.antecesoresC.length];
        int [] patronRespuesta = new int[k.antecesoresC.length];
        int contador = 0;
        for(Object resultado : k.antecesoresC){
            String mensaje = "¿El objeto tiene " + resultado.toString() + "?";
            String titulo = "Infiriendo";
           int respuesta = JOptionPane.showConfirmDialog(null,mensaje,titulo,JOptionPane.YES_NO_OPTION);
           if(respuesta == JOptionPane.YES_OPTION){
               patron[contador] = 1.0;
           }
           contador++;
               
         }
               
        
        patronRespuesta = k.Inferencia(patron);
        resultadoInferencia = resultadoInferencia + "Reglas utilizadas: \n";
        
        if(!k.Mapeo.get(patronRespuesta[0]).equals("Ninguno"))
        for(int i=0;i<patronRespuesta.length;i++){
            if(patronRespuesta[i]!=0){
                   resultadoInferencia = resultadoInferencia + k.MapeoA.get(patronRespuesta[i]);
           //resultadoInferencia  = resultadoInferencia.substring(0,resultadoInferencia.length()-2);
           resultadoInferencia = resultadoInferencia + " > " + k.Mapeo.get(patronRespuesta[i]);           
           resultadoInferencia = resultadoInferencia + "\n";
            }
        }
        
        
        resultadoInferencia = resultadoInferencia + " El resultado es: \n";
        for(int i = 0;i<patronRespuesta.length;i++){
            if(patronRespuesta[i]!=0)
            {
                System.out.println("Clase: "+patronRespuesta[i]);
                if(k.Mapeo.get(patronRespuesta[i])==null)
                    resultadoInferencia = resultadoInferencia + "No se ha encontrado una similitud";
                else
                     resultadoInferencia = resultadoInferencia +k.Mapeo.get(patronRespuesta[i]) + ", ";
            }
        }
        
        resultadoInferencia = resultadoInferencia.substring(0,resultadoInferencia.length()-1);
        areraInferencia.setText(resultadoInferencia);
        
        
    }//GEN-LAST:event_btnInferenciaActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaEntrenamiento;
    private javax.swing.JTextArea areraInferencia;
    private javax.swing.JButton btnDelete;
    private javax.swing.JPanel btnEntrenamiento;
    private javax.swing.JButton btnInferencia;
    private javax.swing.JButton btnInsertaReglas;
    private javax.swing.JButton btnRecuperaReglas;
    private javax.swing.JButton btnUpdateRegla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
